import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async(name,strip=false)=>{
 let source=await readFile(new URL('../tools/workbench/web/'+name,import.meta.url),'utf8');
 if(strip)source=source.replace("import {api} from './session.js';",'const api=()=>{throw Error("unexpected mutation")};');
 return import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
};
const {groupAssets}=await load('asset-versions.js',true);
const original={id:'original',path:'concept.png',location:'candidate',versionGroup:'concept',versionPart:0,versionHidden:true,versionSelected:true};
const selected={...original,id:'V1',path:'snapshot1.png',versionHidden:false};
const latest={...original,id:'V2',path:'snapshot2.png',versionSelected:false};
const game={...latest,id:'game-old',path:'game/concept.png',location:'game',versionHidden:false};
const companion={...selected,id:'side',versionPart:1};
const model={...original,id:'model',versionGroup:'model',versionHidden:false};
const raw=[original,selected,latest,game,companion,model];
assert.deepEqual(groupAssets(raw).map(x=>x.id),['V1','model']);
assert.deepEqual(groupAssets(raw.filter(x=>x.location==='game')).map(x=>x.id),['game-old']);
assert.deepEqual(groupAssets([latest]).map(x=>x.id),['V2']);
assert.equal(groupAssets([{id:'unregistered'},...raw]).length,3);
const {createVersionBrief}=await load('version-brief.js');
const elements=new Map();
const doc={getElementById:id=>{if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,addEventListener(){}});return elements.get(id);}};
const $=doc.getElementById;
const data={versions:{groups:[{id:'concept',title:'Hero',kind:'image',versions:[{id:'V1',number:1,intact:true,note:'first'},{id:'V2',number:2,intact:true,note:'second'}]}]},assets:[]};
const brief=createVersionBrief({getData:()=>data,escape:String,doc});
$('brief-provider').value='image';brief.refresh({group:'concept',parent:'V1'});
$('brief-change-note').value='Use old silhouette';$('brief-reference-role').value='palette';$('brief-extra-reference').value='concept/V2';
const request=brief.request();assert.equal(request.lineage.parent,'V1');assert.equal(request.lineage.references[0].role,'palette');
assert.equal($('native-fields').hidden,false);assert.equal(request.lineage.references[0].version,'V2');
$('brief-provider').value='seedream';brief.update();assert.equal($('native-fields').hidden,true);
assert.match($('brief-lineage-note').textContent,/一张参考图/);
$('brief-asset-group').value='';$('brief-parent').value='';assert.equal(brief.request().lineage.group,null);
console.log('Asset revision grouping, scoped history and pinned revision form passed.');
