import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../tools/workbench/web/asset-categories.js',import.meta.url),'utf8');
const {matchesCategory,matchesFilters,categoryLabel,classificationLabels,effectiveCategory}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const hero={kind:'model',animations:['Idle'],classification:{category:'character',topics:['archviz'],audioKind:''}};
const music={kind:'audio',classification:{category:'audio',audioKind:'music',topics:[]}};
assert(matchesCategory(hero,'all'));assert(matchesCategory(hero,'character'));assert(matchesCategory(hero,'animation'));
assert(!matchesCategory(hero,'weapon'));assert(!matchesCategory(hero,'unclassified'));
assert(matchesFilters(hero,{format:'model',topic:'archviz'}));assert(!matchesFilters(hero,{format:'image'}));
assert(matchesFilters(music,{audio:'music'}));assert(!matchesFilters(music,{audio:'sfx'}));
assert(!matchesFilters(music,{topic:'archviz'}));assert(matchesFilters(music,{}));
assert.equal(categoryLabel(hero,{categories:[{id:'character',label:'人物角色'}]}),'人物角色');
assert.equal(categoryLabel({},{}),'未分类');
const taxonomy={categories:[{id:'character',label:'人物角色'},{id:'animation',label:'动画资源'},{id:'audio',label:'音乐音效'}],audioKinds:{music:'配乐'}};
assert.deepEqual(classificationLabels(hero,taxonomy).map(t=>t.label),['人物角色','含动画']);
assert.deepEqual(classificationLabels(music,taxonomy).map(t=>t.label),['音乐音效','配乐']);
const motion={...hero,meshes:0};
assert.equal(effectiveCategory(motion),'animation');assert(!matchesCategory(motion,'character'));
assert.equal(effectiveCategory({...motion,classification:{category:'character',manual:true}}),'character');
const sharedList=[hero,music];
assert.equal(sharedList.filter(a=>matchesCategory(a,'all')).length,2);
assert.equal(sharedList.filter(a=>matchesCategory(a,'animation')).length,1);
assert.equal(classificationLabels({...hero,classification:{...hero.classification,needsReview:true}},taxonomy).at(-1).label,'分类待核对');
console.log('Asset purpose/format/topic/audio combinations passed.');
