import {createActionPreview} from './action-preview.js';
const fields={start_s:'开始 / 秒',source_in_s:'素材入点 / 秒',source_out_s:'素材出点 / 秒',rate:'播放速度',blend_in_s:'进入 / 淡入 / 秒',blend_out_s:'退出 / 淡出 / 秒',volume:'音量',time_s:'发生时刻 / 秒',end_s:'结束 / 秒',duration_s:'总时长 / 秒'};
const engineNames={unreal:'UE5',unity:'Unity',godot:'Godot',threejs:'Three.js',phaser:'Phaser',web:'网页游戏'};
const clone=x=>JSON.parse(JSON.stringify(x));
const end=c=>c.start_s+(c.source_out_s-c.source_in_s)/c.rate;
const fmt=x=>Number(x).toFixed(3);
export function createActionEditor({root,api,esc,toast,onRunSaved}) {
  let savedSequence=null;
  let active=false,loaded=false,data=null,seq=null,selected='',dirty=false,undo=[],redo=[],zoom=1,t=0,playing=false,raf=0,started=0,offset=0,revision=0;
  let context=null,sources=[],buffers=new Map(),waves=new Map(),reference=null;
  const $=id=>root.querySelector('#'+id);
  const native=createActionPreview({root,api,esc,onSaved:onRunSaved,getData:()=>data&&seq?{sequence:clone(seq),hash:data.hash,preview:data.entry.preview}:null,onTime:value=>{t=Math.min(seq.duration_s,value);paintTime();},onMode:value=>{
    if(value)pause();for(const id of ['ae-draft-audio','ae-play','ae-begin','ae-loop','ae-in','ae-out','ae-reference'])if($(id))$(id).disabled=value;
    if($('ae-reference-panel'))$('ae-reference-panel').hidden=value;
  }});
  root.innerHTML=`<header class="ae-heading"><div><h1>动作时间轴</h1><p>安排动画、声音和操作窗口，然后在引擎中复测。</p></div><span class="ae-tag">片段编辑</span></header>
  <div class="ae-top"><label>动作<select id="ae-action"></select></label><span id="ae-engine"></span><button id="ae-reload" class="button secondary">重新载入</button><span id="ae-status" role="status"></span></div><div id="ae-content"></div>`;
  function status(text){$('ae-status').textContent=text;}
  async function loadList(){try{const result=await api('/api/action-editor');$('ae-action').innerHTML=result.actions.map(a=>`<option value="${esc(a.id)}">${esc(a.title)}</option>`).join('');loaded=true;if(result.actions.length)await load();else $('ae-content').innerHTML='<div class="action-empty"><h2>还没有接入可编辑动作</h2><p>登记项目动作、素材和实际读取配置的引擎组件后，即可在这里安排片段。实机记录页仍可使用。</p></div>';}catch(e){status(e.message);}}
  async function load(){pause();await native.disconnect();const request=++revision;try{const d=await api('/api/action-sequence?id='+$('ae-action').value);if(request!==revision)return;data=d;seq=clone(d.draft&&!d.draft.stale?d.draft.sequence:d.sequence);savedSequence=clone(seq);selected=seq.clips[0]?.id||seq.events[0]?.id;undo=[];redo=[];dirty=false;t=0;reference=d.entry.references?.[0]||null;$('ae-engine').textContent=engineNames[d.entry.engine];render();status(d.draft?.stale?'已载入引擎当前版本；旧草案基于另一版本。':d.draft?'已载入保存的草案':'已载入工程保存配置');await loadAudio();}catch(e){status(e.message);}}
  function item(){return [...seq.clips,...seq.events,...seq.windows].find(c=>c.id===selected);}
  function kind(c){return seq.clips.includes(c)?seq.assets.find(a=>a.id===c.asset).kind:seq.events.includes(c)?'event':'window';}
  function can(id,k){return data.entry.editable?.[id]?.includes(k);}
  function push(){undo.push(clone(seq));if(undo.length>80)undo.shift();redo=[];dirty=true;}
  function changed(){dirty=JSON.stringify(seq)!==JSON.stringify(savedSequence);status(dirty?'草案已修改 · 尚未保存到工程':'已恢复到载入时的参数');draw();inspector();diff();native.edited();}
  function render(){
    $('ae-content').innerHTML=`<div class="ae-studio"><section class="ae-monitor"><div id="ae-native"></div><div id="ae-reference-panel"><div class="ae-monitor-head"><label>实机参考<select id="ae-reference">${(data.entry.references||[]).map((r,i)=>`<option value="${i}">${esc(r.label)}</option>`).join('')}</select></label><span id="ae-reference-note">软件输入 · 录像</span></div>${reference?'<video id="ae-video" playsinline preload="auto"></video>':'<div class="ae-no-video">未关联实机录像</div>'}<p id="ae-preview-note">实机录像作为对齐参考。调整动画后，需应用并重新运行引擎查看新动作。</p></div></section>
    <aside class="ae-inspector"><h2>片段属性</h2><div id="ae-inspector"></div></aside></div>
    <section class="ae-editing"><div class="ae-transport"><button class="button primary" id="ae-play">播放</button><button class="button secondary" id="ae-begin">回到开头</button><output id="ae-time">00.000 / ${fmt(seq.duration_s)} s</output><label><input type="checkbox" id="ae-loop" checked>循环</label><label><input type="checkbox" id="ae-draft-audio">试听草案声音</label><span class="ae-spacer"></span><button class="button secondary" id="ae-undo">撤销</button><button class="button secondary" id="ae-redo">重做</button></div>
    <div class="ae-options"><label>吸附<select id="ae-snap"><option value="0.0333333333333">帧 · 30 fps</option><option value="0.01">10 ms</option><option value="0.001">1 ms</option><option value="0">关闭</option></select></label><label>缩放<input id="ae-zoom" type="range" min="1" max="4" step=".25" value="${zoom}"></label><label>循环起点<input id="ae-in" type="number" min="0" max="${seq.duration_s}" step=".01" value="0"></label><label>终点<input id="ae-out" type="number" min=".01" max="${seq.duration_s}" step=".01" value="${seq.duration_s}"></label></div>
    <div class="ae-scroll"><div id="ae-timeline" tabindex="0" aria-label="可编辑动作时间轴"></div></div>
    <p class="ae-help">拖动条形片段移动时刻，拖两端裁剪。单击标尺定位；选中片段后用 ← → 微调。蓝色为动画，紫色为声音，绿色为操作窗口，菱形为瞬时事件。斜面表示过渡。</p></section>
    <section class="ae-footer"><div><h2>修改预览</h2><p id="ae-diff-summary"></p></div><div class="ae-save"><button class="button secondary" id="ae-save">保存草案</button><button class="button primary" id="ae-apply">保存到工程</button><button class="button secondary" id="ae-restore">恢复上次应用前</button></div><div id="ae-diff"></div><p class="ae-footnote">${esc(data.entry.consumer_note||'项目需有读取此配置的引擎组件。')} 引擎录像保持原样，草案试听不会重制实机画面。</p></section>`;
    bind();setReference();draw();inspector();diff();native.mount();
  }
  function setReference(){if(!reference)return;const v=$('ae-video');if(v){v.src='/api/action-video?id='+reference.run;v.onloadedmetadata=()=>{v.currentTime=(reference.start_s||0)+t;};v.onended=pause;v.onerror=()=>status('实机录像读取失败');}}
  function pause(){playing=false;cancelAnimationFrame(raf);if($('ae-play'))$('ae-play').textContent='播放';$('ae-video')?.pause();stopAudio();}
  function stopAudio(){for(const s of sources){try{s.stop();}catch{}}sources=[];}
  function seek(value){if(native.isConnected()){status("原生预览请使用重放和逐帧控件；此标尺用于定位历史录像。");return;}pause();t=Math.min(seq.duration_s,Math.max(0,value));const v=$('ae-video');if(v&&reference)v.currentTime=t+(reference.start_s||0);paintTime();}
  async function loadAudio(){const request=revision;waves.clear();buffers.clear();for(const a of seq.assets.filter(a=>a.kind==='audio'&&a.preview)){try{const w=await api(`/api/action-waveform?id=${seq.id}&asset=${a.id}`);if(request!==revision)return;waves.set(a.id,w);}catch(e){status('波形未载入：'+e.message);}}if(request===revision)draw();}
  async function prepareAudio(){if(seq.clips.some(c=>{const a=seq.assets.find(a=>a.id===c.asset);return a.kind==='audio'&&!a.preview;}))throw Error('有声音片段未登记实际试听文件');if(!context)context=new AudioContext();await context.resume();const request=revision;for(const a of seq.assets.filter(a=>a.kind==='audio'&&a.preview&&!buffers.has(a.id))){const response=await fetch(`/api/action-audio?id=${seq.id}&asset=${a.id}`);if(!response.ok)throw Error('声音文件无法读取');const buffer=await context.decodeAudioData(await response.arrayBuffer());if(request!==revision)throw Error('动作已切换');buffers.set(a.id,buffer);}}
  function scheduleAudio(){stopAudio();for(const c of seq.clips){const b=buffers.get(c.asset);if(!b||end(c)<=t)continue;const s=context.createBufferSource(),gain=context.createGain();s.buffer=b;s.playbackRate.value=c.rate;s.connect(gain).connect(context.destination);const from=Math.max(t,c.start_s),until=end(c),at=context.currentTime+Math.max(0,c.start_s-t),local=from-c.start_s;
      const level=elapsed=>c.volume*Math.min(1,c.blend_in_s?elapsed/c.blend_in_s:1,c.blend_out_s?(end(c)-c.start_s-elapsed)/c.blend_out_s:1);
      gain.gain.setValueAtTime(Math.max(0,level(local)),at);
      for(const elapsed of [c.blend_in_s,end(c)-c.start_s-c.blend_out_s,end(c)-c.start_s].filter(x=>x>local).sort((a,b)=>a-b))gain.gain.linearRampToValueAtTime(Math.max(0,level(elapsed)),at+elapsed-local);
      s.start(at,c.source_in_s+local*c.rate,(until-from)*c.rate);sources.push(s);
    }}
  async function play(){if(playing){pause();return;}try{if(t>=Number($('ae-out').value))t=Number($('ae-in').value)||0;const audition=$('ae-draft-audio').checked;if(audition)await prepareAudio();if(!active)return;const v=$('ae-video');if(v&&reference){v.muted=audition;v.currentTime=t+(reference.start_s||0);await v.play();}offset=t;started=performance.now();playing=true;if(audition)scheduleAudio();$('ae-play').textContent='暂停';raf=requestAnimationFrame(tick);}catch(e){pause();status(e.message);}}
  function tick(){if(!playing)return;const v=$('ae-video');t=v&&reference&&!v.paused?v.currentTime-(reference.start_s||0):offset+(performance.now()-started)/1000;paintTime();if(t>=Math.min(seq.duration_s,Number($('ae-out').value))){const loop=$('ae-loop').checked;seek(Number($('ae-in').value));if(loop)play();return;}raf=requestAnimationFrame(tick);}
  function paintTime(){$('ae-time').textContent=`${fmt(t)} / ${fmt(seq.duration_s)} s`;root.querySelectorAll('.ae-playhead').forEach(e=>e.style.left=`${100*t/seq.duration_s}%`);}
  function snap(value,exclude){const step=Number($('ae-snap').value);if(!step)return value;let result=Math.round(value/step)*step;const edges=[...seq.events.map(x=>x.time_s),...seq.clips.filter(x=>x.id!==exclude).flatMap(x=>[x.start_s,end(x)]),...seq.windows.filter(x=>x.id!==exclude).flatMap(x=>[x.start_s,x.end_s])];for(const edge of edges){if(Math.abs(edge-value)<Math.min(step,.025))result=edge;}return Math.round(result*1000000)/1000000;}
  function waveform(c){if(!seq.assets.find(a=>a.id===c.asset).preview)return '<span class="ae-no-wave">未登记试听文件</span>';const w=waves.get(c.asset);if(!w)return '<span class="ae-no-wave">波形载入中</span>';const points=[],span=c.source_out_s-c.source_in_s;for(let x=0;x<=160;x++){const k=Math.min(w.peaks.length-1,Math.floor((c.source_in_s+x/160*span)/w.duration_s*w.peaks.length));const a=Math.min(22,w.peaks[k]*48);points.push(`${x},${25-a}`);}for(let x=160;x>=0;x--){const k=Math.min(w.peaks.length-1,Math.floor((c.source_in_s+x/160*span)/w.duration_s*w.peaks.length));points.push(`${x},${25+Math.min(22,w.peaks[k]*48)}`);}return `<svg viewBox="0 0 160 50" preserveAspectRatio="none" aria-label="实际声音波形"><polygon points="${points.join(' ')}"/></svg>`;}
  function draw(){if(!seq)return;const pos=x=>100*x/seq.duration_s;const ticks=[];const step=seq.duration_s>10?1:.25;for(let x=0;x<=seq.duration_s;x+=step)ticks.push(`<span style="left:${pos(x)}%">${x.toFixed(2)}</span>`);
    const lane=(track)=>{const clips=seq.clips.filter(c=>c.track===track.id);return `<div class="ae-lane"><div class="ae-track-title"><i class="${track.kind}"></i><strong>${esc(track.label)}</strong></div><div class="ae-bed" data-track="${track.id}">${clips.map(c=>`<div class="ae-clip ${track.kind} ${c.id===selected?'selected':''}" tabindex="0" role="button" aria-label="${esc(c.label)}片段" data-item="${c.id}" style="left:${pos(c.start_s)}%;width:${pos(end(c)-c.start_s)}%"><span class="ae-fade in" style="width:${100*c.blend_in_s/(end(c)-c.start_s)}%"></span><span class="ae-fade out" style="width:${100*c.blend_out_s/(end(c)-c.start_s)}%"></span>${track.kind==='audio'?waveform(c):''}<b>${esc(c.label)}</b><small>${fmt(c.start_s)}–${fmt(end(c))} s　×${Number(c.rate.toFixed(3))}</small><span class="ae-handle left" data-edge="left"></span><span class="ae-handle right" data-edge="right"></span></div>`).join('')}${seq.windows.filter(c=>c.track===track.id).map(c=>`<div class="ae-clip window ${c.id===selected?'selected':''}" tabindex="0" role="button" aria-label="${esc(c.label)}窗口" data-item="${c.id}" style="left:${pos(c.start_s)}%;width:${pos(c.end_s-c.start_s)}%"><b>${esc(c.label)}</b><small>${fmt(c.start_s)}–${fmt(c.end_s)} s</small><span class="ae-handle left" data-edge="left"></span><span class="ae-handle right" data-edge="right"></span></div>`).join('')}${seq.events.filter(e=>e.track===track.id).map(e=>`<button class="ae-marker ${e.id===selected?'selected':''}" data-item="${e.id}" style="left:${pos(e.time_s)}%" aria-label="${esc(e.label)}事件" title="${esc(e.label)} ${fmt(e.time_s)} s"><span>◆</span><b>${esc(e.label)}</b></button>`).join('')}<div class="ae-playhead"></div></div></div>`;};
    const timeline=$('ae-timeline');timeline.style.width=`${zoom*100}%`;timeline.innerHTML=`<div class="ae-ruler-row"><div class="ae-track-title">轨道 / 秒</div><div id="ae-ruler">${ticks.join('')}<div class="ae-playhead"></div></div></div>${seq.tracks.map(lane).join('')}`;paintTime();
    $('ae-ruler').onpointerdown=e=>{const b=e.currentTarget.getBoundingClientRect();seek((e.clientX-b.left)/b.width*seq.duration_s);};
    timeline.querySelectorAll('[data-item]').forEach(el=>{el.onpointerdown=drag;el.onkeydown=e=>{if(e.key==='Enter'){selected=el.dataset.item;draw();inspector();return;}if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();selected=el.dataset.item;const c=item(),key=kind(c)==='event'?'time_s':'start_s';if(!can(c.id,key))return;push();const delta=(e.key==='ArrowLeft'?-1:1)*(Number($('ae-snap').value)||.001)*(e.shiftKey?10:1);moveItem(c,delta);changed();timeline.querySelector(`[data-item="${c.id}"]`)?.focus();};});
  }
  function moveItem(c,delta){const type=kind(c),last=type==='event'?c.time_s:type==='window'?c.end_s:end(c);delta=Math.max(-(c.time_s??c.start_s),Math.min(seq.duration_s-last,delta));if(type==='event')c.time_s+=delta;else{c.start_s+=delta;if(type==='window')c.end_s+=delta;}}
  function drag(e){if(e.button!==0)return;e.preventDefault();pause();selected=e.currentTarget.dataset.item;const c=item(),original=clone(c),edge=e.target.dataset.edge,type=kind(c),bed=e.currentTarget.closest('.ae-bed'),width=bed.getBoundingClientRect().width,start=e.clientX;let moved=false;
    const key=type==='event'?'time_s':edge?(type==='window'?(edge==='left'?'start_s':'end_s'):(edge==='left'?'source_in_s':'source_out_s')):'start_s';
    draw();inspector();if(!can(c.id,key))return;
    const move=event=>{if(!moved&&Math.abs(event.clientX-start)<2)return;if(!moved){push();moved=true;}Object.assign(c,original);const delta=(event.clientX-start)/width*seq.duration_s;
      if(!edge){const target=snap((c.time_s??c.start_s)+delta,c.id);moveItem(c,target-(c.time_s??c.start_s));}
      else if(type==='window'){if(edge==='left')c.start_s=Math.max(0,Math.min(c.end_s-.01,snap(c.start_s+delta,c.id)));else c.end_s=Math.min(seq.duration_s,Math.max(c.start_s+.01,snap(c.end_s+delta,c.id)));}
      else{const a=seq.assets.find(a=>a.id===c.asset);if(edge==='left'){const s=Math.max(c.start_s-c.source_in_s/c.rate,0,Math.min(end(c)-.01,snap(c.start_s+delta,c.id)));c.source_in_s+=(s-c.start_s)*c.rate;c.start_s=s;}else c.source_out_s=Math.min(a.duration_s,Math.max(c.source_in_s+.01,(Math.min(seq.duration_s,snap(end(c)+delta,c.id))-c.start_s)*c.rate+c.source_in_s));const length=end(c)-c.start_s;c.blend_in_s=Math.min(c.blend_in_s,length/2);c.blend_out_s=Math.min(c.blend_out_s,length-c.blend_in_s);}
      changed();};
    const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});
  }
  function valid(c,type){if(type==='event')return c.time_s<=seq.duration_s;if(type==='window')return c.start_s<c.end_s&&c.end_s<=seq.duration_s;const a=seq.assets.find(a=>a.id===c.asset);return c.rate>=.1&&c.rate<=4&&c.source_in_s<c.source_out_s&&c.source_out_s<=a.duration_s+.0001&&end(c)<=seq.duration_s+.0001&&c.blend_in_s+c.blend_out_s<=end(c)-c.start_s+.0001&&c.volume<=2;}
  function inspector(){const c=item();if(!c){$('ae-inspector').textContent='选择一个片段';return;}const type=kind(c),a=seq.assets.find(a=>a.id===c.asset);const keys=type==='event'?['time_s']:type==='window'?['start_s','end_s']:['start_s','source_in_s','source_out_s','rate','blend_in_s','blend_out_s',...(type==='audio'?['volume']:[])];$('ae-inspector').innerHTML=`<h3>${esc(c.label)}</h3><p class="ae-type">${{animation:'动画片段',audio:'声音片段',event:'瞬时事件',window:'操作窗口'}[type]}</p>${a?`<p class="ae-asset">${esc(a.label)} · ${fmt(a.duration_s)} s</p>`:''}<div class="ae-fields">${keys.map(k=>`<label>${fields[k]}<input data-field="${k}" aria-label="${fields[k]}" type="number" step=".001" min="0" value="${Number(c[k].toFixed(6))}" ${can(c.id,k)?'':'disabled'}></label>`).join('')}</div><button class="button secondary" id="ae-seek-item">定位到片段开始</button>`;
    $('ae-inspector').querySelectorAll('[data-field]').forEach(input=>input.onchange=()=>{pause();const v=Number(input.value);if(!Number.isFinite(v)||v<0){inspector();return;}const candidate={...c,[input.dataset.field]:v};if(!valid(candidate,type)){status('数值超出素材或动作范围，请核对裁剪、速度和过渡时间。');inspector();return;}push();c[input.dataset.field]=v;changed();});$('ae-inspector').querySelectorAll('[data-field]').forEach(input=>input.onkeydown=e=>{if(e.key==='Enter'){input.onchange();}});$('ae-seek-item').onclick=()=>seek(c.time_s??c.start_s);
  }
  function diff(){const changes=[];for(const kind of ['clips','events','windows'])for(const c of seq[kind]){const old=data.sequence[kind].find(x=>x.id===c.id);for(const k in fields)if(k in c&&Math.abs(c[k]-old[k])>.0000001)changes.push(`<tr><td>${esc(c.label)}</td><td>${fields[k]}</td><td>${fmt(old[k])}</td><td>${fmt(c[k])}</td></tr>`);}$('ae-diff-summary').textContent=changes.length?`${changes.length} 项参数修改 · ${dirty?'尚未保存':'草案已保存'}。`:'当前没有参数修改。';$('ae-diff').innerHTML=changes.length?`<table><thead><tr><th>片段</th><th>参数</th><th>工程保存值</th><th>草案值</th></tr></thead><tbody>${changes.join('')}</tbody></table>`:'';$('ae-undo').disabled=!undo.length;$('ae-redo').disabled=!redo.length;$('ae-apply').disabled=!changes.length;$('ae-restore').disabled=!data.history.length||data.history[0].after_hash!==data.hash;}
  async function save(){pause();const snapshot=clone(seq);const result=await api('/api/action-draft',{id:seq.id,base_hash:data.hash,sequence:snapshot});savedSequence=snapshot;dirty=JSON.stringify(seq)!==JSON.stringify(snapshot);status('草案已保存 · 正式工程配置未改变');diff();return result;}
  function bind(){
    $('ae-play').onclick=play;$('ae-begin').onclick=()=>seek(0);$('ae-reference').onchange=()=>{pause();reference=data.entry.references[Number($('ae-reference').value)];setReference();};
    $('ae-draft-audio').onchange=()=>{pause();$('ae-preview-note').textContent=$('ae-draft-audio').checked?'草案试听：原录像已静音，播放调整后的独立声音。画面仍是所选实机参考。':'实机录像作为对齐参考。调整动画后，需应用并重新运行引擎查看新动作。';};
    $('ae-zoom').oninput=e=>{zoom=Number(e.target.value);draw();};
    for(const id of ['ae-in','ae-out'])$(id).onchange=()=>{pause();let lo=Math.max(0,Number($('ae-in').value)||0),hi=Math.min(seq.duration_s,Number($('ae-out').value)||seq.duration_s);if(lo>=hi){lo=0;hi=seq.duration_s;}$('ae-in').value=lo;$('ae-out').value=hi;};
    $('ae-undo').onclick=()=>{if(!undo.length)return;pause();redo.push(clone(seq));seq=undo.pop();changed();};$('ae-redo').onclick=()=>{if(!redo.length)return;pause();undo.push(clone(seq));seq=redo.pop();changed();};
    $('ae-save').onclick=()=>save().catch(e=>status(e.message));
    $('ae-apply').onclick=async()=>{try{const draft=await save();const r=await api('/api/action-apply',{id:seq.id,base_hash:data.hash,draft_hash:draft.draft_hash});await load();status(r.message);toast('已保存到工程 · 重新预览可核对生效配置');}catch(e){status(e.message);}};
    $('ae-restore').onclick=async()=>{try{const r=await api('/api/action-restore',{id:seq.id,base_hash:data.hash,history_id:data.history[0].id});await load();status(r.message);}catch(e){status(e.message);}};
  }
  $('ae-action').onchange=()=>{if(dirty){$('ae-action').value=seq.id;status('先保存草案，再切换动作');return;}load();};
  $('ae-reload').onclick=()=>{if(dirty){status('有未保存修改；先保存草案，或用撤销恢复后重新载入。');return;}load();};
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  return {active(value){active=value;if(value&&!loaded)loadList();if(!value)pause();native.active(value);}};
}
