import {api} from './session.js';
import {seconds,rawTime,duration,mediaTime,alignedOffset,extrema,camera2DCorners} from './observation-math.js';
const $=id=>document.getElementById(id);
const lines=value=>value.split('\n').map(x=>x.trim()).filter(Boolean);
const title={active:'进行中',paused:'已暂停',complete:'记录已完成',cancelled:'已取消',needs_revalidation:'需要重验',pending:'待开展',working:'正在制作',done:'有完成记录',blocked:'有阻碍',current:'当前版本',stale:'历史版本 / 依赖已变'};
const professional={ 'game-preproduction':'制作管理','game-concept':'创意与定位','game-design':'系统策划','game-combat-design':'战斗策划','game-level-design':'关卡策划','game-art-direction':'美术指导','game-character-art':'角色美术','game-environment-art':'场景美术','game-animation-pipeline':'动画','game-vfx-design':'特效','game-audio-design':'音频','game-ui-ux':'UI/UX','game-technical-art':'技术美术','game-technical-design':'技术与工程','game-prototype-validation':'验证'};

export function createProductionReview({escape:esc,toast}){
 let snapshot=null,taskId='',taskDetail=null,observation=null,reference=null,clock='game',now=0,offset=null,referenceClock='',projection='xy',selectedObject='',spatialAnchor=null,zoom=1,pan=[0,0],lastMap=null,requestVersion=0,referenceVersion=0;
 const option=(value,label)=>`<option value="${esc(value)}">${esc(label)}</option>`;
 const list=rows=>rows.length?`<ul>${rows.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="muted">无记录</p>';
 $('production-view').innerHTML=`<header class="page-heading"><div><div class="review-eyebrow">PROJECT / FIVE STAGES</div><h1>项目与阶段</h1><p>本轮目标、实际产物与结束条件。</p></div><div class="pr-actions"><button class="button secondary" id="production-refresh">刷新</button><button class="button primary" id="production-new">建立阶段任务</button></div></header><p id="production-runtime" class="pr-note"></p><div class="pr-layout"><nav id="production-list" class="pr-list" aria-label="阶段任务"></nav><section id="production-detail" class="pr-panel" aria-live="polite"></section></div>`;
 $('observation-view').innerHTML=`<header class="page-heading"><div><div class="review-eyebrow">RUNTIME EVIDENCE</div><h1>运行评审</h1><p>沿对象、位置和时间查看真实记录。</p></div><button class="button secondary" id="observation-refresh">刷新</button></header>
 <div class="pr-controls"><label>当前记录<select id="observation-select"></select></label><label>对照记录<select id="reference-select"></select></label><label>对象<select id="observation-object"></select></label><label>来源时钟<select id="observation-clock"></select></label></div><div id="observation-empty" class="pr-note"></div><div id="observation-body" hidden>
 <div id="observation-context" class="pr-note"></div><div class="pr-controls"><label>当前记录锚点<select id="anchor-current"></select></label><label>对照记录锚点<select id="anchor-reference"></select></label><button class="button secondary" id="align-observations">按所选事件对齐</button><span id="alignment-description">对照时钟尚未对齐</span><label><input type="checkbox" id="same-space">已核对两个记录使用相同空间坐标系</label></div>
 <div class="pr-controls pr-playhead"><button class="button secondary" id="previous-event" aria-label="前一个事件">←</button><input id="observation-time" type="range" min="0" max="1" step="0.001" value="0" aria-label="观察时间"><button class="button secondary" id="next-event" aria-label="后一个事件">→</button><output id="time-label">0.000 s</output></div>
 <div class="pr-evidence-grid"><section class="pr-panel"><div class="pr-actions"><h2>空间与路线</h2><select id="space-projection" aria-label="空间投影"><option value="xy">XY 俯视</option><option value="xz">XZ 剖面</option><option value="yz">YZ 剖面</option></select><button class="button secondary" id="space-reset">复位</button><button class="button secondary" id="space-in" aria-label="放大空间">＋</button><button class="button secondary" id="space-out" aria-label="缩小空间">－</button></div><canvas id="observation-space" width="1000" height="520" aria-label="实际空间与采样路线；滚轮缩放、拖动平移、点击记录批注位置"></canvas><p id="space-caption" class="pr-note"></p></section><section class="pr-panel"><h2>同次运行画面</h2><div id="observation-media" class="pr-media"></div><p id="media-caption" class="pr-note"></p><div id="observation-audio"></div><h3>对照画面</h3><div id="reference-media" class="pr-media"></div><p id="reference-media-caption" class="pr-note"></p><div id="reference-audio"></div></section></div>
 <section class="pr-panel"><h2>事件与参数曲线</h2><canvas id="observation-timeline" width="1400" height="260" aria-label="观测事件时间线"></canvas><div id="curve-selectors" class="pr-controls"></div><canvas id="observation-curves" width="1400" height="260" aria-label="实际参数曲线"></canvas><p class="pr-note">图形最多显示每条曲线 1500 个原始采样点；完整数据保留在记录中。逻辑事件不等于屏幕或声音已经响应。</p><div id="observation-events" class="pr-table-wrap"></div></section>
 <section class="pr-panel"><h2>参数来源与生效值</h2><div id="observation-parameters" class="pr-table-wrap"></div></section>
 <section class="pr-panel"><h2>批注与问题依据</h2><form id="observation-note" class="pr-note-form"><label>作者<input id="note-author" required value="项目评审"></label><label>锚点<select id="note-kind"><option value="time">当前时间</option><option value="position">所选空间位置</option></select></label><label class="pr-wide">观察到的问题<textarea id="note-text" required rows="2" maxlength="4000"></textarea></label><button class="button primary" type="submit">保存版本批注</button></form><p id="note-anchor" class="pr-note"></p><div id="observation-notes"></div></section></div>`;
 const dialog=document.createElement('dialog');dialog.id='production-dialog';dialog.className='pr-dialog';document.body.append(dialog);
 function modal(html){dialog.innerHTML=html;dialog.showModal();dialog.querySelector('[data-dismiss]').onclick=()=>dialog.close();}
 const closeButton='<button type="button" class="button secondary" data-dismiss>关闭</button>';
 async function activate(view){
  try{
   snapshot=await api('/api/production');
   if(view==='production'){
    const runtime=await api('/api/runtime');$('production-runtime').textContent=`工具包 ${runtime.started.version} · ${runtime.started.distribution==='source'?'源码运行':'已分发版本'}${runtime.restart_required?' · 文件已更新，请重启看板服务':''} · ${snapshot.layout.reason}`;
    renderTasks();if(taskId)await loadTask(taskId);renderStandards();renderModels();
   }else{
    const options=snapshot.observations.map(o=>option(o.id,`${o.id} · ${title[o.status]} · ${o.context.engine}`)).join('');
    const prior=$('observation-select').value;$('observation-select').innerHTML=options;$('reference-select').innerHTML=option('','不对照')+options;
    if(snapshot.observations.some(o=>o.id===prior))$('observation-select').value=prior;
    $('observation-empty').textContent=options?'':'尚无已登记的运行记录。通过引擎采集或登记已有证据后刷新；没有记录不代表已经通过。';
    if(snapshot.invalid.length)$('observation-empty').textContent+=' 部分记录无法读取：'+snapshot.invalid.map(x=>x.error).join('；');
    await loadObservation();
   }
  }catch(error){toast(error.message);}
 }
 function renderModels(){
  let panel=$('numeric-models');if(!panel){panel=document.createElement('section');panel.id='numeric-models';panel.className='pr-panel';$('production-view').append(panel);}
  panel.innerHTML='<h2>数值预测与实测</h2><p class="pr-note">模型引用现有参数与运行记录；预测与实测分开，不覆盖游戏权威配置。</p>'+(snapshot.numeric_models||[]).map(row=>{
   if(row.error)return `<p>${esc(row.path)}：${esc(row.error)}</p>`;
   const m=row.model,points=m.samples,actual=m.measurements,xs=[...points.map(p=>p[0]),...actual.map(p=>p.input)],ys=[...points.map(p=>p[1]),...actual.map(p=>p.actual)];
   const a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys),x=v=>50+700*(v-a)/(b-a||1),y=v=>240-210*(v-c)/(d-c||1);
   const line=points.map(p=>`${x(p[0])},${y(p[1])}`).join(' '),marks=actual.map(p=>`<circle cx="${x(p.input)}" cy="${y(p.actual)}" r="5" fill="#c95040"/>`).join('');
   return `<article><h3>${esc(m.title)} · ${esc(title[row.status]||row.status)}</h3><p>${esc(m.basis)}</p>${row.changed.length?list(row.changed.map(p=>'依赖已变：'+p)):''}<svg viewBox="0 0 820 280" role="img" aria-label="${esc(m.title)}预测蓝线与实测红点" style="width:100%;max-height:300px"><path d="M50 30 V240 H770" fill="none" stroke="#99a"/><polyline points="${line}" fill="none" stroke="#276aa5" stroke-width="2"/>${marks}<text x="50" y="270">${a} ${esc(m.input_unit)}</text><text x="690" y="270">${b}</text><text x="5" y="25">${esc(m.output_unit)} ${d}</text></svg><div class="pr-table-wrap"><table><thead><tr><th>输入</th><th>预测</th><th>实测</th><th>差值</th><th>条件</th></tr></thead><tbody>${actual.map(p=>'<tr>'+['input','predicted','actual','difference','conditions'].map(k=>'<td>'+esc(String(p[k]))+'</td>').join('')+'</tr>').join('')}</tbody></table></div>${list(m.conditions)}<code>${esc(row.path)}</code></article>`;
  }).join('')+(!(snapshot.numeric_models||[]).length?'<p>尚未登记模型比较。</p>':'');
 }
 function renderTasks(){
  if(!snapshot.tasks.some(t=>t.id===taskId))taskId=snapshot.tasks[0]?.id||'';
  $('production-list').innerHTML=snapshot.tasks.map(t=>`<button data-task="${esc(t.id)}" class="pr-task ${taskId===t.id?'active':''}"><strong>${esc(t.goal)}</strong><span>${esc(t.id)} · 阶段 ${t.interval.join(' → ')}</span><small>${esc(title[t.effective_state]||t.effective_state)}</small></button>`).join('')+snapshot.legacy_tasks.map(t=>`<p class="pr-note">${esc(t.id)}：原有 Markdown 任务，尚未启用阶段编排，原文保留。</p>`).join('');
  if(!taskId)$('production-detail').innerHTML='<h2>从本轮目标开始</h2><p>选择任意起止阶段，复用已有成果。建立计划不会自动生成游戏或证明品质通过。</p>';
  $('production-list').querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{taskId=b.dataset.task;renderTasks();loadTask(taskId);});
 }
 function renderStandards(){
  let panel=$('production-standards');if(!panel){panel=document.createElement('section');panel.id='production-standards';panel.className='pr-panel';$('production-view').append(panel);}
  const links=snapshot.links;panel.hidden=!links;if(!links)return;
  if(links.error){panel.innerHTML='<h2>项目标准与消费者</h2><p>'+esc(links.error)+'</p>';return;}
  panel.innerHTML=`<h2>项目标准与消费者</h2><p class="pr-note">引用主源：${esc(links.spec)}。这里显示作者源和实际消费者的关系，不另存一套参数。</p><div class="pr-table-wrap"><table><thead><tr><th>约束 / 单位</th><th>来源 / 当前读回</th><th>实际消费者 / 检查</th></tr></thead><tbody>${links.constraints.map(c=>`<tr><td>${esc(c.id)}<br>${esc(c.domain)} · ${esc(c.unit)}</td><td>${esc(c.source.path)} · ${esc(c.source.locator)}<br>${c.resolution==='exact_json_pointer'?esc(JSON.stringify(c.current_value)):'原生或文档来源；未推算数值'}<br>${esc(c.source.provenance)} · ${esc(c.evidence_status)}</td><td>${c.consumers.map(x=>`${esc(x.object)} · ${esc(x.source)} :: ${esc(x.locator)}<br>${esc(x.checks.join('；'))}`).join('<hr>')}</td></tr>`).join('')}</tbody></table></div><h3>版本变化影响</h3>${links.impacts.map(i=>`<details><summary>${esc(i.snapshot)} · ${i.affected.length} 项约束变化</summary>${list(i.affected.flatMap(a=>[a.constraint+' · '+a.reason,...a.consumers.map(c=>c.object+'：'+c.checks.join('；'))]))}</details>`).join('')||'<p class="muted">没有保存过比较基线；不推断历史影响。</p>'}<details><summary>对象与职业接口</summary>${links.objects.map(o=>`<h3>${esc(o.id)} · ${esc(o.title)}</h3>${list((o.links||[]).map(l=>l.role+' · '+l.source+' :: '+l.locator+' · '+l.description))}`).join('')}</details>`;
 }
 async function loadTask(id){
  try{
   const data=await api('/api/production-task?id='+encodeURIComponent(id));if(taskId!==id)return;taskDetail=data;
   const t=data.task,s=data.status;
   $('production-detail').innerHTML=`<div class="pr-actions"><span class="status-pill">${esc(title[s.effective_state]||s.effective_state)}</span><span>${esc(t.id)} · 修订 ${t.revision}</span><button class="button secondary" id="production-edit">更新工作记录</button></div><h2>${esc(t.goal)}</h2><div class="pr-stages">${snapshot.stages.map(stage=>{const active=s.stages.find(x=>x.number===stage.number);return `<div class="${active?'in-scope':'out-scope'}"><b>${stage.number} · ${esc(stage.name||stage.title)}</b><span>${active?(active.complete?'已满足记录条件':'待完成 / 待验证'):'本轮范围外'}</span></div>`;}).join('')}</div><h3>范围与交付</h3>${list(t.objects.map(o=>o.id+' · '+o.title))}${list(t.deliverables)}<h3>实际工作</h3>${t.steps.length?`<div class="pr-table-wrap"><table><thead><tr><th>工作</th><th>主责</th><th>状态 / 依据</th></tr></thead><tbody>${t.steps.map(step=>`<tr><td>${esc(step.id)} · ${esc(step.description)}</td><td>${esc(professional[step.owner]||step.owner)}</td><td>${esc(title[step.state])}<br>${esc(step.note)}${Object.keys(step.outputs).map(p=>`<br><code>${esc(p)}</code>`).join('')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">尚未登记执行步骤。当前只有任务约定。</p>'}<h3>结束条件与缺口</h3>${s.stages.map(stage=>`<details ${stage.complete?'':'open'}><summary>阶段 ${stage.number} · ${stage.complete?'记录条件已满足':'存在缺口'}</summary>${list(stage.problems)}</details>`).join('')}<h3>问题与依赖变化</h3>${list(t.issues.map(i=>i.id+' · '+i.state+' · '+i.reason))}${list(s.changed_inputs.map(p=>'输入版本已变：'+p))}<details><summary>约束、授权与恢复线索</summary>${list(t.constraints)}${list(t.authorization)}<pre>${esc(JSON.stringify(data.recovery.steps,null,2))}</pre></details>`;
   $('production-edit').onclick=editTask;
  }catch(error){toast(error.message);}
 }
 function newTask(){
  const stageOptions=snapshot.stages.map(s=>option(String(s.number),`${s.number} · ${s.name||s.title}`)).join('');
  modal(`<form id="new-stage-task" class="pr-form"><h2>建立本轮任务</h2><label>任务 ID<input name="id" required pattern="[A-Za-z0-9][A-Za-z0-9_-]{0,63}" placeholder="T001"></label><label>本轮目标<textarea name="goal" required rows="2"></textarea></label><div class="pr-controls"><label>起始阶段<select name="start">${stageOptions}</select></label><label>结束阶段<select name="end">${stageOptions}</select></label></div><label>对象（每行 ID | 名称）<textarea name="objects" required rows="3" placeholder="hero | 主角"></textarea></label><label>交付内容（每行一项）<textarea name="deliverables" required rows="3"></textarea></label><label>品质与平台约束<textarea name="constraints" rows="2"></textarea></label><label>现有授权依据<textarea name="authorization" rows="2"></textarea></label><div class="pr-actions">${closeButton}<button type="submit" class="button primary">保存任务约定</button></div></form>`);
  $('new-stage-task').onsubmit=async event=>{event.preventDefault();const f=new FormData(event.target);try{const result=await api('/api/production-task',{action:'create',spec:{id:f.get('id'),goal:f.get('goal'),start_stage:Number(f.get('start')),end_stage:Number(f.get('end')),objects:lines(f.get('objects')).map(v=>{const [id,...rest]=v.split('|');return {id:id.trim(),title:rest.join('|').trim()||id.trim()};}),deliverables:lines(f.get('deliverables')),constraints:lines(f.get('constraints')),authorization:lines(f.get('authorization'))}});taskId=result.id;dialog.close();await activate('production');}catch(error){toast(error.message);}};
 }
 function editTask(){
  const t=taskDetail.task;
  modal(`<form id="update-stage-task" class="pr-form"><h2>更新工作记录 · ${esc(t.id)}</h2><p>保存到同一任务修订；需要实际依据的结果由服务端校验。</p><label>操作<select id="task-operation"><option value="readiness">接手准备度</option><option value="step">工作进度</option><option value="review">阶段检查</option><option value="pause">暂停</option><option value="resume">恢复</option><option value="close">完成本轮</option><option value="advanced">修订计划 / 范围 / 问题</option></select></label><div id="task-operation-fields"></div><label>依据与说明<textarea id="task-operation-reason" required rows="3"></textarea></label><div class="pr-actions">${closeButton}<button class="button primary" type="submit">保存修订</button></div></form>`);
  function fields(){const action=$('task-operation').value;let html='';
   if(['readiness','review'].includes(action))html+=`<label>阶段<select id="task-stage">${t.stages.map(s=>option(String(s.number),String(s.number))).join('')}</select></label>`;
   if(action==='readiness')html+='<label>准备度<select id="task-result"><option value="pending">待核对</option><option value="ready">已具备接手条件</option><option value="blocked">缺少必要输入</option></select></label>';
   if(action==='step')html+=`<label>步骤<select id="task-step">${t.steps.map(s=>option(s.id,s.id+' · '+s.description)).join('')}</select></label><label>进度<select id="task-result"><option value="working">正在制作</option><option value="done">产物与依据已完成</option><option value="blocked">受阻</option><option value="pending">已核对副作用，准备重试</option></select></label><label>产物路径（每行一项）<textarea id="task-outputs" rows="2"></textarea></label>`;
   if(action==='review')html+='<label>检查项<select id="task-check"></select></label><label>判断<select id="task-result"><option value="insufficient">依据不足</option><option value="passed">通过</option><option value="failed">失败</option><option value="not_applicable">不适用，需说明</option></select></label><label>评审人<input id="task-observer" value="项目评审" required></label><label>阶段结论<select id="task-outcome"><option value="pending">尚未确定</option><option value="supported">支持继续 / 交付</option><option value="rejected">评估不支持该方案</option></select></label>';
   if(['readiness','step','review'].includes(action))html+='<label>已登记证据路径（每行一项）<textarea id="task-evidence" rows="2" placeholder=".openaigame/evidence/E001.json"></textarea></label>';
   if(action==='advanced')html='<p>与 CLI 共用操作格式；可提交 plan、amend、issue。保留已执行工作，修订范围需写明已有授权和受影响阶段。</p><textarea id="task-operation-json" rows="12" spellcheck="false">'+esc(JSON.stringify({action:'plan',steps:t.steps.map(({id,stage,objects,owner,description,depends_on,side_effects})=>({id,stage,objects,owner,description,depends_on,side_effects}))},null,2))+'</textarea>';
   $('task-operation-fields').innerHTML=html;
   if(action==='review'){const checks=()=>{$('task-check').innerHTML=t.stages.find(s=>s.number===Number($('task-stage').value)).requirements.map(c=>option(c.id,c.description)).join('');};$('task-stage').onchange=checks;checks();}
  }
  $('task-operation').onchange=fields;fields();
  $('update-stage-task').onsubmit=async event=>{event.preventDefault();try{const action=$('task-operation').value;let operation={action,reason:$('task-operation-reason').value};if(action==='advanced')operation={...JSON.parse($('task-operation-json').value),reason:operation.reason};if(['readiness','review'].includes(action))operation.stage=Number($('task-stage').value);if(['readiness','step','review'].includes(action))operation.evidence=lines($('task-evidence').value);if(action==='readiness')operation.status=$('task-result').value;if(action==='step')Object.assign(operation,{id:$('task-step').value,state:$('task-result').value,outputs:lines($('task-outputs').value)});if(action==='review')Object.assign(operation,{check:$('task-check').value,result:$('task-result').value,observer:$('task-observer').value,outcome:$('task-outcome').value});await api('/api/production-task',{action:'update',id:t.id,revision:t.revision,operation});dialog.close();await activate('production');}catch(error){toast(error.message);}};
 }
 const currentEvents=()=>observation?.data.events.filter(e=>e.clock===clock&&(!selectedObject||e.object===selectedObject))||[];
 const maxTime=data=>duration(data,clock);
 async function loadObservation(){
  const revision=++requestVersion,id=$('observation-select').value;if(!id){$('observation-body').hidden=true;return;}
  try{const row=await api('/api/observation?id='+encodeURIComponent(id));if(revision!==requestVersion)return;observation=row;reference=null;offset=null;referenceClock='';$('same-space').checked=false;zoom=1;pan=[0,0];spatialAnchor=null;
   const d=row.data;clock=d.clocks[0]?.id||'';selectedObject=d.objects[0]?.id||'';
   $('observation-body').hidden=false;$('observation-object').innerHTML=option('','全部对象')+d.objects.map(o=>option(o.id,o.label)).join('');$('observation-object').value=selectedObject;
   $('observation-clock').innerHTML=d.clocks.map(c=>option(c.id,c.id+' · '+c.unit)).join('');$('observation-time').max=maxTime(d);now=0;$('observation-time').value=0;
   $('reference-select').value='';$('anchor-reference').innerHTML='';$('alignment-description').textContent='对照时钟尚未对齐';
   $('observation-context').innerHTML=`<strong>${esc(title[row.status])} · ${esc(d.context.engine)} ${esc(d.context.engine_version)}</strong><p>${esc(d.context.method)} · 输入：${esc(d.context.input_mode)} · 构建：${esc(d.context.build)}</p><p>${esc(d.context.conditions.join('；'))}</p><p>${esc(d.context.sampling_overhead)}</p>${list(d.limitations)}${row.changed.length?list(row.changed.map(p=>'依赖已变：'+p)):''}`;
   renderAnchors();renderParameters();renderNotes();render();
  }catch(error){$('observation-body').hidden=true;toast(error.message);}
 }
 function renderAnchors(){
  $('anchor-current').innerHTML=currentEvents().map(e=>option(e.id,`${e.event} · ${seconds(observation.data,e.clock,e.time).toFixed(3)} s`)).join('');
  $('curve-selectors').innerHTML=`<label>曲线<select id="curve-current">${option('','请选择曲线')}${(observation.data.curves||[]).filter(c=>c.clock===clock&&(!selectedObject||c.object===selectedObject)).map(c=>option(c.id,c.id+' · '+c.unit)).join('')}</select></label>`;
  $('curve-current').onchange=drawCurves;
 }
 function renderParameters(){const rows=(row,label)=>row?(row.data.parameters||[]).map(p=>`<tr><td>${label}</td><td>${esc(p.object)} / ${esc(p.id)}</td><td>${esc(String(p.value))} ${esc(p.unit)}</td><td>${esc(p.provenance)}</td><td>${esc(p.source)}<br>${esc(p.conditions)}${p.overrides?'<br>覆盖：'+esc(p.overrides.join(' → ')):''}</td></tr>`).join(''):'';$('observation-parameters').innerHTML='<table><thead><tr><th>记录</th><th>参数</th><th>值</th><th>来源类型</th><th>权威源 / 条件</th></tr></thead><tbody>'+rows(observation,'当前')+rows(reference,'对照')+'</tbody></table>';}
 function renderNotes(){
    $('observation-notes').innerHTML=observation.notes.map(n=>`<article class="pr-saved-note"><strong>${esc(n.author)} · ${esc(n.object)}</strong><p>${esc(n.text)}</p><small>${esc(title[n.status])} · ${esc(JSON.stringify(n.anchor))}</small><code>.openaigame/review-notes/${esc(n.id)}.json</code><button class="button secondary" data-link-note="${esc(n.id)}" ${n.status==='stale'?'disabled':''}>关联为任务问题</button></article>`).join('')||'<p class="muted">选择对象，在时间线或空间中定位后保存批注。</p>';
    $('observation-notes').querySelectorAll('[data-link-note]').forEach(button=>button.onclick=()=>linkNote(button.dataset.linkNote));
   }
   async function linkNote(id){try{
    const data=await api('/api/production'),note=observation.notes.find(n=>n.id===id),eligible=data.tasks.filter(t=>t.objects.some(o=>o.id===note.object));
    if(!eligible.length)throw Error('没有包含该观察对象的任务，请先在项目与阶段中登记任务范围');
    let dialog=$('note-link-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='note-link-dialog';dialog.style.cssText='max-width:640px;width:90vw;border:1px solid #ccd;border-radius:12px;padding:24px';document.body.append(dialog);}
    dialog.innerHTML=`<form><h2>把批注关联到任务问题</h2><p>${esc(note.text)}</p><label>任务<select name="task">${eligible.map(t=>option(t.id,t.id+' · '+t.goal)).join('')}</select></label><label>问题 ID<input name="issue" value="ISSUE-${esc(id.slice(-8))}" required></label><label>受影响阶段（逗号分隔）<input name="stages" required placeholder="例如 3,4"></label><p class="muted">将保存当前证据并使所选阶段需复核。未涉及的阶段保留原记录。</p><button class="button" type="submit">关联问题</button><button class="button secondary" type="button" data-close>取消</button></form>`;
    dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const form=new FormData(e.target),task=await api('/api/production-task?id='+encodeURIComponent(form.get('task'))),stages=String(form.get('stages')).split(',').map(v=>Number(v.trim()));await api('/api/review-note-link',{note:id,task:task.task.id,revision:task.task.revision,issue:form.get('issue'),stages});dialog.close();toast('已关联当前任务问题和证据');}catch(error){toast(error.message);}};dialog.showModal();
   }catch(error){toast(error.message);}}

 function render(){if(!observation)return;$('time-label').textContent=now.toFixed(3)+' s';$('note-anchor').textContent=spatialAnchor?'空间锚点：'+spatialAnchor.map(x=>x.toFixed(2)).join(', '):'时间锚点：'+now.toFixed(3)+' s · '+clock;drawSpace();drawTimeline();drawCurves();renderMedia();const events=currentEvents();$('observation-events').innerHTML=`<table><thead><tr><th>时间</th><th>对象</th><th>事件</th><th>实际读回</th></tr></thead><tbody>${events.slice(0,500).map(e=>`<tr class="${Math.abs(seconds(observation.data,e.clock,e.time)-now)<.025?'selected':''}"><td><button class="pr-time" data-time="${seconds(observation.data,e.clock,e.time)}">${seconds(observation.data,e.clock,e.time).toFixed(3)} s</button></td><td>${esc(e.object)}</td><td>${esc(e.event)}</td><td>${esc(JSON.stringify(e.data||{}))}</td></tr>`).join('')}</tbody></table>${events.length>500?'<p>表格显示前 500 项，完整记录仍用于图形。</p>':''}`;$('observation-events').querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>seek(Number(b.dataset.time)));}
 function seek(value){now=Math.max(0,Math.min(maxTime(observation.data),value));$('observation-time').value=now;render();}
 function clearCanvas(id){const canvas=$(id),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f7f9fc';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='15px sans-serif';return [canvas,ctx];}
 function drawTimeline(){const [canvas,ctx]=clearCanvas('observation-timeline'),duration=maxTime(observation.data),w=canvas.width-100;const plot=(data,events,y,color,shift=0)=>{ctx.strokeStyle=color;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(50,y);ctx.lineTo(canvas.width-50,y);ctx.stroke();for(const e of events){const x=50+(seconds(data,e.clock,e.time)-shift)/duration*w;ctx.fillRect(x-2,y-10,4,20);} };plot(observation.data,currentEvents(),90,'#335cdb');ctx.fillText('当前 / '+clock,50,40);if(reference&&offset!==null){const rc=referenceClock;plot(reference.data,reference.data.events.filter(e=>e.clock===rc),180,'#c37b22',offset);ctx.fillStyle='#c37b22';ctx.fillText('对照 / 所选锚点时钟',50,145);}ctx.strokeStyle='#de384f';const x=50+now/duration*w;ctx.beginPath();ctx.moveTo(x,10);ctx.lineTo(x,240);ctx.stroke();ctx.fillStyle='#6a7486';ctx.fillText(`0 s — ${duration.toFixed(3)} s`,50,248);}
 function drawCurves(){const [canvas,ctx]=clearCanvas('observation-curves');const c=observation?.data.curves?.find(c=>c.id===$('curve-current')?.value);if(!c){ctx.fillStyle='#667085';ctx.fillText('选择一条带单位的采样曲线',35,45);return;}const duration=maxTime(observation.data),other=reference?.data.curves?.find(r=>r.id===c.id&&r.unit===c.unit&&r.clock===referenceClock),values=[...c.samples.map(x=>x[1]),...(other&&offset!==null?other.samples.map(x=>x[1]):[])],[low,high]=extrema(values),range=high-low||1;function plot(data,curve,color,shift){ctx.strokeStyle=color;ctx.beginPath();const step=Math.max(1,Math.ceil(curve.samples.length/1500));for(let i=0;i<curve.samples.length;i+=step){const [t,v]=curve.samples[i],x=70+(seconds(data,curve.clock,t)-shift)/duration*(canvas.width-120),y=220-(v-low)/range*170;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}plot(observation.data,c,'#335cdb',0);if(other&&offset!==null)plot(reference.data,other,'#c37b22',offset);ctx.fillStyle='#4c596e';ctx.fillText(`${c.unit} · ${low.toFixed(3)} … ${high.toFixed(3)}`,25,28);}
 function drawSpace(){const [canvas,ctx]=clearCanvas('observation-space'),space=observation?.data.space;if(!space){ctx.fillStyle='#667085';ctx.fillText('本次记录未采集空间',35,50);$('space-caption').textContent='空间未测';return;}const axes=space.dimensions===2?[0,1]:projection==='xz'?[0,2]:projection==='yz'?[1,2]:[0,1];const points=space.objects.flatMap(o=>o.bounds||[o.position]).concat((space.routes||[]).flatMap(r=>r.samples.map(s=>s.slice(1))));if(!points.length)return;const min=axes.map(a=>extrema(points.map(p=>p[a]))[0]),max=axes.map(a=>extrema(points.map(p=>p[a]))[1]),scale=Math.min((canvas.width-100)/Math.max(1,max[0]-min[0]),(canvas.height-100)/Math.max(1,max[1]-min[1]))*zoom,center=axes.map((a,i)=>(min[i]+max[i])/2);const point=p=>[(p[axes[0]]-center[0])*scale+canvas.width/2+pan[0],(space.dimensions===2?1:-1)*(p[axes[1]]-center[1])*scale+canvas.height/2+pan[1]];lastMap={axes,center,scale,sign:space.dimensions===2?1:-1};
  const shapes=(sp,color,dashed=false)=>{ctx.setLineDash(dashed?[8,5]:[]);for(const o of sp.objects){const p=point(o.position);ctx.strokeStyle=o.id===selectedObject?'#2258db':color;ctx.fillStyle=o.id===selectedObject?'#dbe7ff':'#e3e8ef';if(o.vertices?.length){ctx.beginPath();if(o.edges?.length){for(const [a,b] of o.edges){ctx.moveTo(...point(o.vertices[a]));ctx.lineTo(...point(o.vertices[b]));}}else{o.vertices.forEach((v,i)=>i?ctx.lineTo(...point(v)):ctx.moveTo(...point(v)));if(o.vertices.length>2)ctx.closePath();}ctx.stroke();}else if(o.bounds){const a=point(o.bounds[0]),b=point(o.bounds[1]);ctx.fillRect(Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]));ctx.strokeRect(Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]));}else{ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();}ctx.fillStyle=color;if(!o.id.includes('/')||o.id===selectedObject)ctx.fillText(o.label||o.id.split('/').pop(),p[0]+7,p[1]-9);}ctx.setLineDash([]);};
  shapes(space,'#586c88');if($('same-space').checked&&reference?.data.space&&reference.data.space.unit===space.unit&&reference.data.space.dimensions===space.dimensions)shapes(reference.data.space,'#c37b22',true);
  for(const route of space.routes||[]){if(selectedObject&&route.object!==selectedObject)continue;ctx.strokeStyle=route.measurement==='model'?'#ad8e61':'#1e9a85';ctx.beginPath();let last=null;route.samples.forEach((sample,i)=>{const p=point(sample.slice(1));i?ctx.lineTo(...p):ctx.moveTo(...p);if(route.clock===clock&&seconds(observation.data,route.clock,sample[0])<=now)last=p;});ctx.stroke();if(last){ctx.fillStyle='#de384f';ctx.beginPath();ctx.arc(...last,7,0,Math.PI*2);ctx.fill();}}
  const latestQueries=new Map();for(const q of space.queries||[]){if(q.clock===clock&&seconds(observation.data,q.clock,q.time)<=now)latestQueries.set(q.id,q);}
    for(const q of latestQueries.values()){ctx.strokeStyle=q.blocked?'#bd4a32':'#55806a';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(...point(q.start));ctx.lineTo(...point(q.end));ctx.stroke();ctx.setLineDash([]);if(q.point){ctx.fillStyle='#bd4a32';ctx.beginPath();ctx.arc(...point(q.point),4,0,Math.PI*2);ctx.fill();}}
    for(const camera of space.objects.filter(o=>o.projection)){const pr=camera.projection;if(space.dimensions===2&&pr.viewport_size&&pr.zoom&&pr.screen_center){const corners=camera2DCorners(pr).map(point);ctx.strokeStyle='#824dc0';ctx.beginPath();ctx.moveTo(...corners[0]);corners.slice(1).forEach(v=>ctx.lineTo(...v));ctx.closePath();ctx.stroke();}else if(pr.world&&pr.field_of_view){const q=pr.world.rotation_xyzw,rotate=v=>{const u=q.slice(0,3),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],c=cross(u,v),cc=cross(u,c);return v.map((x,i)=>x+2*(q[3]*c[i]+cc[i]));},origin=pr.world.position,depth=500,half=depth*Math.tan(pr.field_of_view*Math.PI/360),corners=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([y,z])=>rotate([depth,y*half,z*half/(pr.aspect_ratio||1)]).map((v,i)=>v+origin[i]));ctx.strokeStyle='#824dc0';ctx.setLineDash([6,3]);for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(...point(origin));ctx.lineTo(...point(corners[i]));ctx.lineTo(...point(corners[(i+1)%4]));ctx.stroke();}ctx.setLineDash([]);}}
    if(spatialAnchor){const p=point(spatialAnchor);ctx.strokeStyle='#de384f';ctx.strokeRect(p[0]-8,p[1]-8,16,16);}
  $('space-caption').textContent=`${space.axes} · ${space.unit} · ${space.objects.length} 个采集对象。矩形为边界，轮廓为声明形状；${space.dimensions===2?'紫色矩形为实际相机视口':'紫色相机视锥按500cm展示（非裁剪距离）'}；红/绿线为阻挡/畅通射线。路线类型：${[...new Set((space.routes||[]).map(r=>r.measurement))].join('、')||'未测'}。拖动平移，点击设空间批注。`;
 }
 function mediaPanel(record,sourceClock,time,panel,caption){
  const container=$(panel);
  if(!record||!sourceClock||time===null){container.innerHTML='<p class="muted">选择对照记录并对齐事件后显示。</p>';container.dataset.url='';$(caption).textContent='未对齐';return;}
  const matches=(record.data.media||[]).map((m,i)=>({m,i})).filter(({m})=>m.clock===sourceClock&&m.anchors.length);
  const chosen=matches.filter(({m})=>m.kind==='image').sort((a,b)=>Math.abs(seconds(record.data,sourceClock,a.m.anchors[0][0])-time)-Math.abs(seconds(record.data,sourceClock,b.m.anchors[0][0])-time))[0]||matches[0];
  if(!chosen){container.innerHTML='<p class="muted">该时钟没有已登记的画面或音频。</p>';container.dataset.url='';$(caption).textContent='画面 / 声音未测';return;}
  const {m,i}=chosen,url='/api/observation-media?id='+encodeURIComponent(record.id)+'&index='+i,tag=m.kind==='image'?'img':m.kind==='audio'?'audio':'video';
  if(container.dataset.url!==url){container.dataset.url=url;container.innerHTML=`<${tag} src="${url}" ${tag==='img'?'alt="本次运行证据帧"':'controls preload="metadata"'}></${tag}>`;}
  const media=container.querySelector('video,audio');let aligned=true;
  if(media){const at=mediaTime(m.anchors,rawTime(record.data,sourceClock,time));aligned=at!==null;if(aligned&&Math.abs(media.currentTime-at)>.05)media.currentTime=at;}
  $(caption).textContent=(record.status==='stale'?'历史版本 · ':'')+m.description+' · 音频：'+m.audio_coverage+(aligned?'':' · 当前时间不在已知映射区间内，未推算媒体位置');
 }
 function audioTracks(record,sourceClock,time,id){
  const host=$(id),key=(record?.id||'')+':'+sourceClock;
  if(host.dataset.record!==key){host.dataset.record=key;host.innerHTML=record?(record.data.media||[]).map((m,i)=>({m,i})).filter(({m})=>m.kind==='audio'&&m.clock===sourceClock).map(({m,i})=>`<figure><audio controls preload="metadata" data-media-index="${i}" src="/api/observation-media?id=${encodeURIComponent(record.id)}&index=${i}" aria-label="${esc(m.description)}" style="width:100%"></audio><figcaption>${esc(m.description)}${m.anchors.length<2?' · 只有起点锚点，请独立试听；不推算完整同步关系':''}</figcaption></figure>`).join(''):'';}
  if(time!==null&&record)host.querySelectorAll('audio').forEach(audio=>{const m=record.data.media[Number(audio.dataset.mediaIndex)],at=mediaTime(m.anchors,rawTime(record.data,sourceClock,time));if(at!==null&&Math.abs(audio.currentTime-at)>.05)audio.currentTime=at;});
 }
 function renderMedia(){mediaPanel(observation,clock,now,'observation-media','media-caption');mediaPanel(reference,referenceClock,offset===null?null:now+offset,'reference-media','reference-media-caption');audioTracks(observation,clock,now,'observation-audio');audioTracks(reference,referenceClock,offset===null?null:now+offset,'reference-audio');}
 $('production-refresh').onclick=()=>activate('production');$('production-new').onclick=newTask;$('observation-refresh').onclick=()=>activate('observation');$('observation-select').onchange=loadObservation;
 $('observation-object').onchange=()=>{selectedObject=$('observation-object').value;spatialAnchor=null;offset=null;referenceClock='';$('alignment-description').textContent='对象已改变，需要重新选择锚点对齐';renderAnchors();render();};$('observation-clock').onchange=()=>{clock=$('observation-clock').value;offset=null;referenceClock='';renderAnchors();render();};$('observation-time').oninput=()=>seek(Number($('observation-time').value));
 $('reference-select').onchange=async()=>{try{const version=++referenceVersion,currentVersion=requestVersion,id=$('reference-select').value;const loaded=id?await api('/api/observation?id='+encodeURIComponent(id)):null;if(version!==referenceVersion||currentVersion!==requestVersion)return;reference=loaded;offset=null;referenceClock='';$('same-space').checked=false;$('anchor-reference').innerHTML=reference?reference.data.events.map(e=>option(e.id,`${e.object} / ${e.event} · ${e.clock} · ${seconds(reference.data,e.clock,e.time).toFixed(3)} s`)).join(''):'';$('alignment-description').textContent='对照时钟尚未对齐；空间需核对坐标系后再叠加';renderParameters();render();}catch(error){toast(error.message);}};
 $('align-observations').onclick=()=>{const a=currentEvents().find(e=>e.id===$('anchor-current').value),b=reference?.data.events.find(e=>e.id===$('anchor-reference').value);if(!a||!b){toast('请在两次记录中选择实际观测到的事件');return;}const alignment=alignedOffset(observation.data,a.id,reference.data,b.id);offset=alignment.seconds;referenceClock=alignment.rightClock;$('alignment-description').textContent=`人工选定事件锚点 · 对照减 ${offset.toFixed(3)} s · 只做平移，不推算时钟漂移`;render();};
 const jump=direction=>{const times=currentEvents().map(e=>seconds(observation.data,e.clock,e.time));seek(direction>0?(times.find(t=>t>now+.0001)??maxTime(observation.data)):([...times].reverse().find(t=>t<now-.0001)??0));};$('previous-event').onclick=()=>jump(-1);$('next-event').onclick=()=>jump(1);
 ['anchor-current','anchor-reference'].forEach(id=>$(id).onchange=()=>{offset=null;referenceClock='';$('alignment-description').textContent='锚点已改动，请重新对齐';render();});
   $('same-space').onchange=drawSpace;
 $('space-projection').onchange=()=>{projection=$('space-projection').value;zoom=1;pan=[0,0];drawSpace();};$('space-reset').onclick=()=>{zoom=1;pan=[0,0];drawSpace();};$('space-in').onclick=()=>{zoom=Math.min(20,zoom*1.3);drawSpace();};$('space-out').onclick=()=>{zoom=Math.max(.1,zoom/1.3);drawSpace();};
 const spatial=$('observation-space');let drag=null;spatial.onpointerdown=e=>{spatial.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,pan:[...pan],moved:false};};spatial.onpointermove=e=>{if(!drag)return;const rect=spatial.getBoundingClientRect(),dx=(e.clientX-drag.x)*spatial.width/rect.width,dy=(e.clientY-drag.y)*spatial.height/rect.height;drag.moved ||= Math.abs(dx)+Math.abs(dy)>4;pan=[drag.pan[0]+dx,drag.pan[1]+dy];drawSpace();};spatial.onpointerup=e=>{if(drag&&!drag.moved&&lastMap&&observation?.data.space){const rect=spatial.getBoundingClientRect(),x=(e.clientX-rect.left)*spatial.width/rect.width,y=(e.clientY-rect.top)*spatial.height/rect.height,m=lastMap;spatialAnchor=[...(observation.data.space.objects.find(o=>o.id===selectedObject)?.position||Array(observation.data.space.dimensions).fill(0))];spatialAnchor[m.axes[0]]=(x-spatial.width/2-pan[0])/m.scale+m.center[0];spatialAnchor[m.axes[1]]=(y-spatial.height/2-pan[1])/m.scale/m.sign+m.center[1];render();}drag=null;};spatial.onwheel=e=>{e.preventDefault();zoom=Math.max(.1,Math.min(20,zoom*(e.deltaY>0?.9:1.1)));drawSpace();};
 $('observation-timeline').onclick=e=>{const rect=e.target.getBoundingClientRect();seek(((e.clientX-rect.left)*1400/rect.width-50)/1300*maxTime(observation.data));};
 $('observation-note').onsubmit=async e=>{e.preventDefault();try{if(!selectedObject)throw Error('请先选择具体对象');const kind=$('note-kind').value;if(kind==='position'&&!spatialAnchor)throw Error('请先点击空间图选择位置');const note={id:'N'+crypto.randomUUID().replaceAll('-',''),observation:observation.id,object:selectedObject,text:$('note-text').value,author:$('note-author').value,anchor:kind==='time'?{kind,clock,time:rawTime(observation.data,clock,now)}:{kind,position:spatialAnchor}};await api('/api/review-note',note);observation=await api('/api/observation?id='+encodeURIComponent(observation.id));$('note-text').value='';renderNotes();toast('已保存批注及来源版本');}catch(error){toast(error.message);}};
 return {activate};
}
